import type { NextPage } from 'next'
import Head from 'next/head'
import { useContext } from 'react';
import { useForm } from 'react-hook-form'
import { AuthContext } from '../contexts/AuthContext';

const Home: NextPage = () => {

  const { register, handleSubmit } = useForm();
  const { signIn } = useContext(AuthContext)

  async function handleSignIn(data: any) {
    //here is the best place to put some validation about the sign in
    await signIn(data)
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>

        <form action="" onSubmit={handleSubmit(handleSignIn)}>
          <input
            {...register('email')}
            type="email"
            name="email"
            id="email"
            placeholder='Type your e-mail...' />

          <input
            {...register('password')}
            type="password"
            name="password"
            id="password" />

          <input type="submit" value="submit" />

        </form>

      </main>

    </div>
  )
}

export default Home
